Insert into list_items (index, list_id, text, done, link) values
(0, 1, 'Vietnamesisk fläskfärs i salladsblad', 'false', ''),
(1, 1, 'Carbonarapasta', 'false', ''),
(2, 1, 'Flapsteak med fransk potatissallad', 'false', ''),
(3, 1, 'Köttfärskebab i pita', 'false', ''),
(4, 1, 'Gremolatapasta', 'false', ''),
(5, 1, 'Färsbiffar med grekisk sallad', 'false', ''),
(6, 1, 'Asiatiska fiskbiffar med nudelsallad', 'false', ''),
(7, 1, 'Fisksoppa m bröd', 'true', ''),
(8, 1, 'Fisksoppa m vitlöksyoughurt & bröd', 'true', ''),
(9, 1, 'Lammbullar, zucchini, lök & babyspenat m vitlök', 'true', ''),
(10, 1, 'Sön: Kycklingben med grekisk sallad', 'true', ''),
(11, 1, 'T: Hallomiburgare m pommes', 'true', ''),
(12, 1, 'O: Viltfärsbiffar m grekisk sallad o tzatziki', 'true', ''),
(13, 1, 'F: Räkmacka', 'true', ''),
(14, 1, 'Tonfisk med nudelsallad', 'true', ''),
(15, 1, 'S: Skinkstek m matig sallad', 'true', ''),
(16, 1, 'Lunch: Tortillas med tonfiskröra, äpple & grönt', 'true', ''),
(17, 1, 'Lunch: Korv m bröd', 'true', ''),
(18, 1, 'Lunch: Tortillas m äggröra, tomat och basilika& smootie', 'true', ''),
(19, 1, 'Månd:  Sötpotatis med fetaost, granatäpple, vitlöksmayo, chilistekta svarta bönor och kycklingben. Efterrätt hemgjord glass', 'true', ''),
(20, 1, 'Tis lunch: Falafel på stan', 'true', ''),
(21, 1, 'Tisdag: Malmö breweri', 'true', ''),
(22, 1, 'Ons lunch: Hallongården', 'true', ''),
(23, 1, 'Onsdag: Picnic och burgare', 'true', ''),
(24, 1, 'Torsmorgon: Våfflor m varmrökt lax och bär/sylt med grädde', 'true', ''),

(0, 2, 'Lunch', 'true', ''),
(1, 2, 'Räkor', 'true', ''),
(2, 2, 'Pintsa', 'true', ''),
(3, 2, 'Plastpåsar', 'true', ''),
(4, 2, 'Nudlar', 'true', ''),
(5, 2, 'Sweetchilisås', 'true', ''),
(6, 2, 'Oliver', 'true', ''),
(7, 2, 'Bordssmör', 'true', ''),
(8, 2, 'Pålägg', 'true', ''),
(9, 2, 'Ost', 'true', ''),
(10, 2, 'Matyoghurt', 'true', ''),
(11, 2, 'Yoghurt', 'true', ''),
(12, 2, 'Grädde', 'true', ''),
(13, 2, 'Jos', 'true', ''),
(14, 2, 'Kaffe', 'true', ''),
(15, 2, 'GF bröd', 'true', ''),
(16, 2, 'Soppåsar', 'true', ''),
(17, 2, 'Toalettpapper', 'true', ''),
(18, 2, 'Städservetter', 'true', ''),
(19, 2, 'Öl', 'true', ''),
(20, 2, 'Smör', 'true', ''),
(21, 2, 'Rökt salt', 'true', ''),
(22, 2, 'Paprika', 'true', ''),
(23, 2, 'Gurka', 'true', ''),
(24, 2, 'Tomat', 'true', ''),
(25, 2, 'Mjölk', 'true', ''),
(26, 2, 'Ägg', 'true', ''),
(27, 2, 'Ingefärsshot', 'true', ''),
(28, 2, 'Keso', 'true', ''),
(29, 2, 'Ost', 'true', ''),
(30, 2, 'Färskost', 'true', ''),
(31, 2, 'Pålägg', 'true', ''),
(32, 2, 'Fetaost', 'true', ''),
(33, 2, 'Mozzarella', 'true', ''),
(34, 2, 'Banan', 'true', ''),
(35, 2, 'Persilja', 'true', ''),
(36, 2, 'Mjölk', 'true', ''),
(37, 2, 'Is', 'true', ''),
(38, 2, 'Baguetter', 'true', ''),
(39, 2, 'Sallad', 'true', ''),
(40, 2, 'Rapsolja', 'true', ''),
(41, 2, 'Matyoghurt', 'true', ''),
(42, 2, 'Solrosfrön', 'true', ''),
(43, 2, 'Wasabi', 'true', ''),
(44, 2, 'Luncher', 'true', ''),
(45, 2, 'Handtvål', 'true', ''),
(46, 2, 'Handdiskmedel', 'true', ''),

(0, 3, 'Systrar & Bröder, Östra Rönneholmsvägen - frukost, lunch  & fika', 'false', ''),
(1, 3, 'Nybergs hembageti & Konditori, Adelsgatan - Fika', 'false', ''),
(2, 3, 'Konditori Hollandia, Södra förstadsgatan - Fika & räkmacka', 'false', ''),
(3, 3, 'Barr, Södra förstadsgatan - Lunch & fika (nästan allt GF)', 'false', ''),
(4, 3, 'Brunchoteket, Stortorget - Brunch', 'false', ''),
(5, 3, 'Lemon Garden, Einar Hansens esplanad  - Brunch och fika', 'false', ''),
(6, 3, 'Scandwich, Kristiandsgatan - matiga mackor', 'false', ''),
(7, 3, 'Atrium, Skvadrongatan - Frukost, lunch & fika', 'false', ''),
(8, 3, 'Piccolo mondo, Lillatorg - Pasta', 'false', ''),
(9, 3, 'Drumbar, Lilla torg - Pubmat ex gf Fish and chips', 'false', ''),
(10, 3, 'Dirty Taco, Södra Vallgatan - Tacos', 'false', ''),
(11, 3, 'Addicted burgers, foodtruck - Burgers', 'false', ''),
(12, 3, 'Casual streetfood, Bergsgatan - Burgare', 'false', ''),
(13, 3, 'Benne pastabar, Malmborgsgatan 6 och Öglegången 6', 'false', ''),
(14, 3, '400 grader, Södra skolgatan - finpizza', 'false', ''),
(15, 3, 'Lamare pizzeria, Dammfrigatan - hämtpizza', 'false', ''),
(16, 3, 'Pizzerai Rex, Nobelvägen - Fulpizza', 'false', ''),
(17, 3, 'Pizzeria Verona, Söderkullagatan - fulpizza', 'false', ''),
(18, 3, 'Far i hatten, Folkets park - Pizza', 'false', ''),
(19, 3, 'Spot, Stora Nygatan - Finpizza', 'false', ''),
(20, 3, 'Enoclub, Skomakaregatan - pizza', 'false', ''),
(21, 3, 'Västergatan, Västergatan 16 - Finmiddag med fast meny', 'false', ''),
(22, 3, 'Mutantur, Erik Dahlbergsgatan - Finmiddag', 'false', ''),
(23, 3, 'Kin Long, Rådmansgatan - Kinesiskt', 'false', ''),
(24, 3, 'La Trattoria, Östra tullgatan - Sicilianskt', 'false', ''),
(25, 3, 'Kol & coktail, Kalendegatan - kolgrill', 'false', ''),
(26, 3, 'Quan, Mäster Johansgatan - asiatiskt', 'false', ''),
(27, 3, 'Grand Italian, Dag Hammarskiölds torg - Italienskt (dock ej pasta o pizza)', 'false', ''),
(28, 3, 'Art of Spices, Bergsgatan - Indiskt', 'false', ''),
(29, 3, 'Atmosfär, Fersens väg - Fin middag', 'false', ''),
(30, 3, 'Spoonery - Take away luncher', 'false', ''),
(31, 3, 'Holy green, 4 ställen - Sallad allt GF', 'false', ''),
(32, 3, 'Kohai sushi, Föreningsgatan - Sushi', 'false', ''),
(33, 3, 'Aiko sushi, 3 adresser- Supersushi', 'false', ''),

(0, 4, 'Inlägg', 'false', 'https://www.instagram.com/reel/DJYCwY5yx6_/?igsh=MWt6bzB4djM3b2V5bA=='),
(1, 4, 'Låda', 'false', 'https://www.instagram.com/reel/DLEx__lR8t7/?igsh=MTJnbTYxazkzd3N4cw=='),
(2, 4, 'Fotoram', 'false', 'https://www.instagram.com/reel/DFCl1qQIyX6/?igsh=cnI2dDg1aHQ1Mmlp'),
(3, 4, 'Snyggt inlägg', 'false', 'https://www.instagram.com/reel/DL7T1kis2Ue/?igsh=dXRjdGNkcW0wZGdl'),
(4, 4, 'Cool hörnhylla', 'false', 'https://www.instagram.com/p/DLjfGJJRYEW/?igsh=YjhnbmE3dXRpNzFj'),
(5, 4, 'Papperskort', 'false', 'https://www.instagram.com/reel/DLge3xGiTY8/?igsh=cG41c2N1eGY5anlx'),
(6, 4, 'Tandborstställ', 'false', 'https://www.instagram.com/p/DLOt8jNTCYd/?igsh=cWlwbnRxNHIybHc='),
(7, 4, 'Hundramp', 'false', 'https://www.instagram.com/reel/DLYaERWSZf2/?igsh=MTdrYW5mM2dpcXdh'),
(8, 4, 'Snygg bokhylla', 'false', 'https://www.instagram.com/reel/DKC0y4GzDim/?igsh=MXhtdGlvNjY1M3MwdQ=='),
(9, 4, 'Fyrvägsbord', 'false', 'https://www.instagram.com/reel/DHPvQSczgRS/?igsh=MWR2NzZucTJ5azBqOQ=='),
(10, 4, 'Höj o sänk skrivbord', 'false', 'https://www.instagram.com/reel/DJ5MOTLyMoD/?igsh=bzQ3MmxqbTF2enZu'),
(11, 4, 'Vägghängare 3', 'false', 'https://www.instagram.com/reel/DGDg9sCxA9l/?igsh=MWcwc2t3dDZhdWRzaA=='),
(12, 4, 'Vägghängare 2', 'false', 'https://www.instagram.com/reel/DIemCJ2Taz7/?igsh=MWZibzU0eWE5anNjYg=='),
(13, 4, 'Vägghängare', 'false', 'https://www.instagram.com/reel/DDK4G8-M17a/?igsh=MWdrZGRlbnMwcXBhdQ=='),
(14, 4, 'Pall', 'false', 'https://www.instagram.com/reel/DI6dy2uTk-N/?igsh=MW80ZDAydmtsaDV0bA=='),
(15, 4, 'Hylla', 'false', 'https://www.instagram.com/reel/DGNuNESS3wt/?igsh=MXU2dTcyYTMyd2Q0dg=='),
(16, 4, 'Thors beer opener', 'false', 'https://www.instagram.com/reel/DDWhAqAP4nB/?igsh=MTduZ2hvcWNzdXpw'),
(17, 4, 'Mini pedistal', 'false', 'https://www.instagram.com/reel/DIRHHcoTTGJ/?igsh=MWJpcmt0dXRqZjBoNQ=='),
(18, 4, 'Cool inlay', 'false', 'https://www.instagram.com/reel/DDjQeIiS_Ac/?igsh=MWRlcGc0MXR5emV1ZQ=='),
(19, 4, 'Pretty join', 'false', 'https://www.instagram.com/reel/DGxwojDysok/?igsh=MWQ2MmpmaW16ZXlybw=='),
(20, 4, 'Table', 'false', 'https://www.instagram.com/reel/DHTF6YfT68B/?igsh=MTRhNHkyc2hwbXRnaQ=='),
(21, 4, 'Pedistal', 'false', 'https://www.instagram.com/reel/DHAIZBMzz4n/?igsh=NWVqbzUyemV5N3gy'),
(22, 4, 'Cool shelf', 'false', 'https://www.instagram.com/reel/DDPSmEgoIbZ/?igsh=bDAycGt1YmNpenJx'),
(23, 4, 'Fin lampa', 'false', 'https://www.instagram.com/reel/DFaJPEnS6Tj/?igsh=MWpxdGIycmZlZHliOQ=='),
(24, 4, 'Pedistal 2', 'false', 'https://www.instagram.com/reel/DHIXf1nsz5o/?igsh=MWc3c3h4dzJqazNmcg=='),
(25, 4, 'Rotate open box', 'false', 'https://www.instagram.com/reel/DBMVaGwoJUb/?igsh=MW1iY2szMTNrdnRvNQ=='),
(26, 4, 'Rotate open box 2', 'false', 'https://www.instagram.com/reel/DGcRi7dSadG/?igsh=azM3bXI0ZmhpN2R1'),
(27, 4, 'Wall table', 'false', 'https://www.instagram.com/reel/DFE0HJpTIzs/?igsh=MWFxcW8ybncxbHBycg=='),
(28, 4, 'Matbar till Svante', 'false', ''),
(29, 4, 'Tamburmajor', 'false', ''),
(30, 4, 'Barskåp', 'false', ''),
(31, 4, 'Dosett', 'false', ''),
(32, 4, 'Hushållsrullehållare', 'true', ''),
(33, 4, 'Fia bokstöd', 'true', ''),
(34, 4, 'Fotohyllor', 'true', ''),
(35, 4, 'Super router jig', 'true', 'https://www.instagram.com/reel/DBA-10hy1xe/?igsh=MWNnM3hhaHBtbnJocQ=='),
(36, 4, 'Sticksåg som slip', 'true', 'https://www.instagram.com/reel/DFKjOh7SyK5/?igsh=MTRtcjB0cnAxN3F5dA=='),
(37, 4, 'Skärbräda till lilla vasken', 'true', ''),
(38, 4, 'Bas till doftolje lykta', 'true', ''),

(0, 5, 'Jig', 'false', 'https://www.instagram.com/reel/DIgdJU3zhln/?igsh=dDdhaDJ4cnFlaHJl'),
(1, 5, 'Thin strips', 'false', 'https://www.instagram.com/reel/DLLGytcAW5Y/?igsh=MnN5aGNrbnQ1cDh4'),
(2, 5, 'Hörninlägg', 'false', 'https://www.instagram.com/reel/DKo23Y2SE7S/?igsh=MTI5cjkxeXA4cTAxeQ=='),
(3, 5, 'Möbeljig', 'false', 'https://www.instagram.com/reel/DJT4UDvSNzo/?igsh=ZTBhNmxobzRwaW9r'),
(4, 5, 'Sanding block', 'false', 'https://www.instagram.com/reel/DJC7sSoh8tE/?igsh=MTd4dnlhdDhseGt1NQ=='),
(5, 5, 'Table saw jig', 'false', 'https://www.instagram.com/reel/DJDgAFqSqzC/?igsh=MW5xMW1scHoyNThzYQ=='),
(6, 5, 'Strip cut jig', 'false', 'https://www.instagram.com/reel/DII2i65JDh1/?igsh=NzgwOHN1YjJ4b2I1'),
(7, 5, 'More jigs', 'false', 'https://www.instagram.com/reel/DGrYDmHKUqs/?igsh=eTh1aWhwbTluNXBv'),
(8, 5, 'Cut sled', 'false', 'https://www.instagram.com/reel/DCi_crEzZzU/?igsh=MTBsN251OXpicWZm'),
(9, 5, 'Circle router jig part 2', 'false', 'https://www.instagram.com/reel/DBoLobcy233/?igsh=MTYwN3NhZ3ZtcXlnZA=='),
(10, 5, 'Circle router jig', 'false', 'https://www.instagram.com/reel/DBd5U8qSjCa/?igsh=dXQxeThzZGlkMm4y'),
(11, 5, 'Cut jigs', 'false', 'https://www.instagram.com/reel/DGk78dvIzhN/?igsh=MWJnYm8xOGp1amxx'),
(12, 5, '90 corner jig', 'false', 'https://www.instagram.com/reel/DD_770_u80L/?igsh=OHZ5dzh1Nmtsamd5'),
(13, 5, 'Center jig', 'false', 'https://www.instagram.com/reel/DAzHWY8yvzD/?igsh=MTg5dmN3ampnbmlxZw=='),
(14, 5, 'Joinery jig', 'false', 'https://www.instagram.com/reel/DAlPGtdy34h/?igsh=MTZpbmk1MzB0eXk5Zw=='),
(15, 5, 'Borrjig', 'false', 'https://www.instagram.com/reel/DADrejjSovM/?igsh=cXU3NHNsbDVvcmVk'),
(16, 5, 'Router jig', 'false', 'https://www.instagram.com/reel/DBLUghSy5mL/?igsh=ZHBxODVrczh2OW53'),
(17, 5, 'Custom clamps', 'false', 'https://www.instagram.com/reel/DEKO15bIQ9l/?igsh=MWNncG1rMTVsMGxpNQ=='),
(18, 5, 'Bend wood', 'false', 'https://www.instagram.com/reel/DF7vGlCOiO9/?igsh=MXhubWN4djAzbXc1MQ=='),
(19, 5, 'Layering', 'false', 'https://www.instagram.com/reel/DCMVWy2pOpF/?igsh=MTdqMGoycnlxYmd6NA=='),
(20, 5, 'Router table', 'false', 'https://www.instagram.com/reel/DC54a9JzZqI/?igsh=MXRuNWI5MjNzeWJvbA=='),
(21, 5, 'Half laps', 'false', 'https://www.instagram.com/reel/DAY4Cz-oR3d/?igsh=NjE2emFzZTI0NmRj'),
(22, 5, 'Dovetail joint', 'false', 'https://www.instagram.com/reel/DHgjZfCqzet/?igsh=MWF5YjBsbnVnZHo5cg=='),

(0, 6, 'Al components', 'false', 'https://ai-sdk.dev/elements/overview'),
(1, 6, 'Rest c#', 'false', 'https://m.youtube.com/watch?v=38GNKtclDdE&t=1s&pp=2AEBkAIB'),
(2, 6, 'Db local + cloud', 'false', 'https://dexie.org/'),
(3, 6, 'Typescript config settings', 'false', 'https://2ality.com/2025/01/tsconfig-json.html'),
(4, 6, 'EF json columns', 'false', 'https://www.thereformedprogrammer.net/a-detailed-look-at-ef-cores-json-column-feature/'),
(5, 6, 'Bra komponenter', 'false', 'https://dev.to/composiodev/25-top-open-source-tools-for-building-web-apps-you-cant-afford-to-miss-in-2025-5005'),
(6, 6, 'Sirikarta', 'false', 'https://www.google.com/mymaps/viewer?mid=15AxmKqcx2a70FsfZWbZlTxJxRT6f1tw&hl=sv'),
(7, 6, 'Playwright', 'false', 'https://dev.to/aswani25/integrating-playwright-with-cicd-pipelines-1g1m#step-three'),
(8, 6, 'Remove props based on interface', 'false', 'https://dev.to/hichemtab-tech/beyond-type-safety-making-typescript-smarter-by-building-a-runtime-picker-26d5'),
(9, 6, 'React 19, use hook', 'false', 'https://dev.to/aidanldev/how-to-use-use-the-new-react-19-hook-4ah5'),
(10, 6, 'Vite react dev stack', 'false', 'https://dev.to/singhamandeep007/building-a-production-ready-react-vite-typescript-boilerplate-4ifh'),
(11, 6, 'Jwt + routing', 'false', 'https://dev.to/sanjayttg/jwt-authentication-in-react-with-react-router-1d03'),
(12, 6, 'Auth web', 'false', 'https://www.robinwieruch.de/how-to-roll-your-own-auth/?utm_source=tldrwebdev'),
(13, 6, 'Accessability', 'false', 'https://dev.to/tolgee_i18n/8-powerful-open-source-tools-for-creating-accessible-web-apps-ig3'),
(14, 6, 'Local storage', 'false', 'https://rxdb.info/articles/localstorage-indexeddb-cookies-opfs-sqlite-wasm.html?utm_source=tldrwebdev'),
(15, 6, 'Vercel hooks for data fetching', 'false', 'Https://github.com/vercel/swr'),
(16, 6, 'React PWA', 'false', 'https://www.freecodecamp.org/news/how-to-create-a-nextjs-pwa/'),
(17, 6, 'Check if a key exists in JavaScript object', 'false', 'https://dev.to/developerhub/level-up-your-javascript-mastering-object-property-checks-1d4h'),
(18, 6, '2-sites-to-become-a-better-dev', 'false', 'https://dev.to/kochiyama/2-sites-to-become-a-better-developer-2f9j'),
(19, 6, 'Websockets', 'false', 'https://www.freecodecamp.org/news/learn-websockets-socket-io/'),
(20, 6, '30+ appideas', 'false', 'https://dev.to/copilotkit/30-app-ideas-with-complete-source-code-5f76'),
(21, 6, 'REST API with Postgres', 'false', 'https://dev.to/encore/build-and-deploy-a-rest-api-with-postgres-database-in-typescript-2h0n'),
(22, 6, 'Responsive design', 'false', 'https://dev.to/jaredcodes/finally-understand-responsive-design-3con'),
(23, 6, 'Rxjs', 'false', 'https://rxjs.dev/guide/overview'),
(24, 6, 'Offline enabled todo', 'false', 'https://dev.to/sh20raj/building-an-offline-enabled-to-do-list-web-app-89j'),
(25, 6, 'Vite + firebase', 'false', 'https://dev.to/thebuildguy/building-an-entire-fullstack-project-with-firebase-10-and-react-vite-dfe'),
(26, 6, 'Jwt security', 'false', 'https://dev.to/aymanepraxe/mastering-jwt-security-2kgn'),
(27, 6, 'react component patterns', 'false', 'https://dev.to/fpaghar/react-component-design-patterns-part-1-5f0g'),
(28, 6, 'Typescript custom types', 'false', 'https://dev.to/antonzo/10-sustom-utility-types-for-typescript-projects-48pe'),
(29, 6, 'Next js + signalR', 'false', 'https://blog.logrocket.com/integrating-next-js-signalr/'),
(30, 6, '17 react libs', 'false', 'https://dev.to/copilotkit/libraries-you-should-know-if-you-build-with-react-1807'),
(31, 6, 'API gateway node', 'false', 'https://www.freecodecamp.org/news/build-a-custom-api-gateway-with-node-js/'),
(32, 6, 'cms Google Sheet', 'false', 'https://www.freecodecamp.org/news/how-to-build-a-basic-cms-with-google-sheets-and-reactjs/'),
(33, 6, 'API test cypress', 'false', 'https://dev.to/m4rri4nne/api-testing-with-cypress-part-i-2k3i'),
(34, 6, 'dev flutter app', 'false', 'https://dev.to/happyer/developing-a-flutter-app-from-0-to-1-35dp'),
(35, 6, '.net 8 testing', 'false', 'https://www.hanselman.com/blog/updating-to-net-8-updating-to-ihostbuilder-and-running-playwright-tests-within-nunit-headless-or-headed-on-any-os'),
(36, 6, 'infinite scroll', 'false', 'https://dev.to/kevin-uehara/2-react-query-infinite-scroll-1mg8'),

(0, 7, 'Vietnamesisk fläskfärs i salladsblad', 'false', 'https://www.koket.se/vietnamesisk-flaskfars-i-salladsblad'),
(1, 7, 'Friterad hasselbackspotatis med löjrom och syrad grädde', 'false', 'https://alltommat.expressen.se/recept/friterad-hasselbackspotatis-med-lojrom-och-syrad-gradde/?didomiConfig.notice.enable=false'),
(2, 7, 'Festfint med fasan', 'false', 'https://alltommat.expressen.se/recept/festfint-med-fasan/?didomiConfig.notice.enable=false'),
(3, 7, 'Clementinkyckling', 'false', 'https://www.ica.se/recept/chilirostade-kycklinglar-med-klementiner-715748/'),
(4, 7, 'Morotskaka', 'false', 'https://glutenfriagodsaker.allas.se/baka-glutenfritt/glutenfri-morotskaka-basta-receptet/'),
(5, 7, 'Macrons', 'false', 'https://taysta.se/macarons-recept?srsltid=AfmBOoo9YIUBQjZ6TEawXkaBIsrfmH_gim4LrdeyFY94x-jQRaPD3UFC'),
(6, 7, 'Rabarberlikör', 'false', 'https://adamantkitchen.com/rhubarb-liqueur/'),

(0, 8, 'Drosselmeyer ljusstake', 'false', ''),
(1, 8, 'Gröna silverörhängen', 'false', 'https://www.ornament.se/products/huggie-orhangen-hangsmycke-med-gron-sten-creoler-ringar-i-silvrigt-kirurgiskt-stal?srsltid=AfmBOoqk1KQ85UsV-qc0GxANJqPwsESaR6Pp6upEm9VMzS_fnjknsfd8'),
(2, 8, 'Lego - tavla galax', 'false', ''),
(3, 8, 'Lego - minifigursautomat', 'false', ''),
(4, 8, 'Didrikson Umi pile fleece tröja', 'false', ''),
(5, 8, 'Silverring från Efva Atling', 'false', 'https://www.efvaattling.com/sv/p/ring-around-ring-silver/?gad_source=1&gclid=Cj0KCQjwkN--BhDkARIsAD_mnIpHsBqnQto5ua7AssyeM9hYpi8QjGy0PxBP6CF62yvz4iJdpMlHumoaAplnEALw_wcB'),
(6, 8, 'Sampletl loom bordsvävstol', 'false', 'https://gudrunsullbod.com/produkt/komplett-vavkit-the-complete-weaving-kit/'),
(7, 8, 'Vattenflaska -Airup', 'false', ''),
(8, 8, 'Gröna stora temuggar', 'false', ''),
(9, 8, 'Smörklocka i keramik', 'false', ''),
(10, 8, 'Konrogrill', 'false', ''),
(11, 8, 'Pizzastål från Kockums', 'false', ''),
(12, 8, 'Mandolin bäst i test!', 'true', ''),
(13, 8, 'Tårtor, kakor, bröd från KEA-bageri av Madelein Olsson', 'true', ''),
(14, 8, 'Omaggio svart/vit rller vit/vit stor vas', 'true', ''),
(15, 8, 'Champangekylare', 'true', ''),

(0, 9, 'Epidavros, Grekland - en sjunken stad med snorkling', 'false', '')